### ISSUE TITLE
About Principle Axes of Ineria

### ISSUE THREAD

**Issue by MunLee001** [marco-hinojosa/HST-ADCS#1]
Hi ! 
I don't understand why diag([J11, J22, J33]) to [x-axis, z-axis, y-axis], not to [x-axis, y-axis, z-axis]?
Can you help me ?

Excepting your reply!
Best!
Thanks!

**Comment by MMM-L** [comment]
> Hi ! I don't understand why diag([J11, J22, J33]) to [x-axis, z-axis, y-axis], not to [x-axis, y-axis, z-axis]? Can you help me ?
> 
> Excepting your reply! Best! Thanks!

Becaus I think omega is to  [x-axis, y-axis, z-axis] ?
